<script>
  import PageHeading from "../../shared/PageHeading.svelte";
  import Subheading from "../../shared/Subheading.svelte";
  import Paragraph from "../../shared/Paragraph.svelte";
</script>

<PageHeading>Boomi - data vis</PageHeading>

<iframe title="Boomi - data vis" width="100%" height="800px" src="https://main.dticqtqdkpoh7.amplifyapp.com/"></iframe>

<Paragraph>This is a data visualisation created for the Financial Times' company Longitude.</Paragraph>

<Paragraph>It was created in Svelte with heavy use of custom SVG. Naturally, largest part of this project was mapping the data to the dot positions.</Paragraph>

<Paragraph>The dot positions are pre-processed from raw json data. I set up a node script that watches for changes in my data-processing files and outputs new data whenever there are changes.</Paragraph>

<Paragraph>This is a relatively simple approach to optimising performance, as it takes away the need for the client to process this data, instead it can just be selected from arrays based on user interaction.</Paragraph>

<Paragraph>Performance was always going to be the hardest part of this project, with each user interaction triggering changes to over 1000 nodes. Svelte was a great fit for this project.</Paragraph>

<Subheading>Mobile</Subheading>

<Paragraph>For mobile users I copied the SVGs generated by the svelte front end, took them into Adobe Illustrator, moved groups around a bit so they would fit better, then exported to PNG. I made use of css scroll-snap to give a nice mobile-friendly feel to moving between slides.</Paragraph>


<style>
  iframe {
    margin-bottom: 1rem;
    border: 1px solid black;
    padding: 6px;
    box-shadow: 3px 3px black;
  }
</style>